### ISSUE TITLE
One sample hypothesis testing - gap function

### ISSUE THREAD

**Issue by mortenpettersson** [American-Institutes-for-Research/EdSurvey#26]
Hello,

Let’s say, that I have the ICILS dataset and a binary variable SEX (coded: 1=GIRL, 0=BOY). I know the proportion of girls in the population, μ_0 =0.5, and want to test whether the sample proportion of girls differ from the population proportion. 

As far as I know, the gap analysis works by specifying an outcome variable and the two groups you want to compare: gap(variable, data, groupA = "default", groupB = "default").

Is it possible to specify the gap function in order to test a sample proportion against a known population proportion?

**Comment by yuqiliao** [comment]
Hi Morten,

Thanks for using EdSurvey and for submitting your question here! I can take a stab at this question.

I understand that you wanted to make a comparison between the percentage of girls from the ICILS dataset and the percentage of girls in the population. Currently, you cannot make such a comparison using EdSurvey's `gap` function because the `gap` function can only help you make comparisons between groups that are related to the sample data (in your example, it's the ICILS data). For example, you can use `gap` to compare the percentage of girls vs the percentage boys from the ICILS data, or the percentage of girls vs everyone in the ICILS data.

For your case, you can do a simple t-test to compare the percentage of girls from the ICILS data (note that you need to first get this value using EdSurvey's `edsurveyTable` or `gap` function) and a known percentage from the population. The formula is 
![image](https://user-images.githubusercontent.com/11021157/145865601-4aa78ce0-713e-4930-b6ee-38b15693191e.png)

Where ![image](https://user-images.githubusercontent.com/11021157/145865685-c7f2a467-d08c-4a66-8de2-ce452d6195ef.png) is the estimated value (e.g. the percent of girls from ICILS sample that you could get using EdSurvey's functions such as `edsurveyTable` or `gap`), ![image](https://user-images.githubusercontent.com/11021157/145865732-082dc4ea-5208-4380-a730-76d159fb76c4.png) is the value that you want to test against (e.g. percent of girls in census, which is μ_0 =0.5 in your example), and ![image](https://user-images.githubusercontent.com/11021157/145865810-a910034e-9be1-4bad-8054-06babb503cba.png) is the standard error from EdSurvey's `edsurveyTable` or `gap` function.

Hope this helps! The EdSurvey team is also happy to consider updating the `gap` function so it supports such comparisons  natively, if you could help explain the importance/need/popularity of such comparisons among the research community. Thanks!

**Comment by yuqiliao** [comment]
Closing this issue as Morten mentioned in an email that this is resolved.
